# Generated by Django 5.1.7 on 2025-03-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwapp', '0003_remove_comment_created_remove_post_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='continues_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
